// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzJ62M51ni0FWhG631jfLh4e1Ou-c2ag',
    appId: '1:913048897728:web:4f076beb44b20956230525',
    messagingSenderId: '913048897728',
    projectId: 'clepyapp',
    authDomain: 'clepyapp.firebaseapp.com',
    storageBucket: 'clepyapp.appspot.com',
    measurementId: 'G-7SWDC53L5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjed_w77vbZRGWe5weSc7Po7kQA-350r4',
    appId: '1:913048897728:android:dc5308aa89f422ea230525',
    messagingSenderId: '913048897728',
    projectId: 'clepyapp',
    storageBucket: 'clepyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdv5liie-vRhLDgyKCbm8RDblIDwtyXjQ',
    appId: '1:913048897728:ios:6e390af0c80aead1230525',
    messagingSenderId: '913048897728',
    projectId: 'clepyapp',
    storageBucket: 'clepyapp.appspot.com',
    androidClientId: '913048897728-u6rnc7pvgfg6fntgung1mq1hhlu90q4f.apps.googleusercontent.com',
    iosClientId: '913048897728-b3v3uai9bpsqki6ehb417faf3gb1iufg.apps.googleusercontent.com',
    iosBundleId: 'br.com.clepy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdv5liie-vRhLDgyKCbm8RDblIDwtyXjQ',
    appId: '1:913048897728:ios:6e390af0c80aead1230525',
    messagingSenderId: '913048897728',
    projectId: 'clepyapp',
    storageBucket: 'clepyapp.appspot.com',
    androidClientId: '913048897728-u6rnc7pvgfg6fntgung1mq1hhlu90q4f.apps.googleusercontent.com',
    iosClientId: '913048897728-b3v3uai9bpsqki6ehb417faf3gb1iufg.apps.googleusercontent.com',
    iosBundleId: 'br.com.clepy',
  );
}
